export const SPECIES_CONFIG = {
  bovino: {
    nombre: 'Bovinos', emoji: '🐄', color: '#1B6B3C',
    gestacion_dias: 283, maduracion_meses: 15,
    categorias: ['vaca', 'toro', 'becerro', 'becerra', 'novillo', 'vaquilla', 'semental'],
    razas: ['Brahman', 'Suizo', 'Nelore', 'Holstein', 'Simmental', 'Gyr', 'Charolais', 'Angus', 'Hereford', 'Sardo Negro', 'Indobrasil', 'Cruza'],
    condicion_corporal: { min: 1, max: 9 },
    tipos_produccion: ['carne', 'leche', 'doble_proposito', 'semental', 'engorda'],
    tiene_leche: true, tiene_famacha: false, tiene_lote: false, tiene_colmena: false,
    vacunas: ['Brucelosis (RB51/S19)', 'Clostridiosis', 'Rabia', 'Pasteurelosis', 'Leptospirosis', 'IBR/DVB/PI3', 'Carbón sintomático'],
    kpis: ['tasa_preñez', 'dias_abiertos', 'ipp', 'tasa_destete', 'gdp', 'mortalidad', 'produccion_leche'],
  },
  porcino: {
    nombre: 'Porcinos', emoji: '🐖', color: '#D81B60',
    gestacion_dias: 114, maduracion_meses: 7,
    categorias: ['marrana', 'verraco', 'lechon', 'cerdo_engorda', 'reemplazo', 'desecho'],
    razas: ['Yorkshire', 'Landrace', 'Duroc', 'Hampshire', 'Pietrain', 'Cruza F1', 'Cruza terminal', 'Pelón mexicano'],
    condicion_corporal: { min: 1, max: 5 },
    tipos_produccion: ['reproductor', 'engorda', 'reemplazo', 'traspatio'],
    tiene_leche: false, tiene_famacha: false, tiene_lote: false, tiene_colmena: false,
    vacunas: ['Parvovirus', 'Leptospira', 'E.coli', 'Mycoplasma', 'Erisipela', 'Circovirus'],
    kpis: ['psy', 'dnp', 'tasa_paricion', 'nacidos_vivos', 'mortalidad_predestete', 'fcr', 'gdp'],
  },
  ovino: {
    nombre: 'Ovinos', emoji: '🐑', color: '#5D4037',
    gestacion_dias: 150, maduracion_meses: 8,
    categorias: ['borrega', 'borrego', 'carnero', 'cordero', 'cordera', 'primal'],
    razas: ['Pelibuey', 'Blackbelly', 'Dorper', 'Katahdin', 'Suffolk', 'Hampshire', 'Cruza', 'Criollo'],
    condicion_corporal: { min: 1, max: 5 },
    tipos_produccion: ['carne', 'lana', 'doble_proposito', 'traspatio'],
    tiene_leche: false, tiene_famacha: true, tiene_lote: false, tiene_colmena: false,
    vacunas: ['Clostridiosis', 'Brucelosis (Rev-1)', 'Pasteurelosis'],
    kpis: ['prolificidad', 'tasa_destete', 'ipp', 'peso_destete', 'gdp', 'mortalidad'],
  },
  caprino: {
    nombre: 'Caprinos', emoji: '🐐', color: '#795548',
    gestacion_dias: 150, maduracion_meses: 8,
    categorias: ['cabra', 'macho_cabrio', 'cabrito', 'cabrita', 'chiva', 'primal'],
    razas: ['Boer', 'Nubia', 'Saanen', 'Toggenburg', 'Alpina', 'Murciana-Granadina', 'Cruza', 'Criollo'],
    condicion_corporal: { min: 1, max: 5 },
    tipos_produccion: ['carne', 'leche', 'doble_proposito', 'traspatio'],
    tiene_leche: true, tiene_famacha: true, tiene_lote: false, tiene_colmena: false,
    vacunas: ['Clostridiosis', 'Brucelosis (Rev-1)', 'Pasteurelosis', 'Enterotoxemia'],
    kpis: ['prolificidad', 'tasa_destete', 'produccion_leche', 'gdp', 'mortalidad'],
  },
  ave: {
    nombre: 'Aves', emoji: '🐔', color: '#E65100',
    gestacion_dias: 21, maduracion_meses: 5,
    categorias: ['gallina', 'gallo', 'pollo_engorda', 'pollita', 'guajolote', 'reproductora'],
    razas: ['Hy-Line', 'Lohmann', 'Isa Brown', 'Ross 308', 'Cobb 500', 'Plymouth Rock', 'Rhode Island', 'Criollo', 'Guajolote criollo'],
    condicion_corporal: { min: 1, max: 5 },
    tipos_produccion: ['postura', 'engorda', 'reproductoras', 'doble_proposito', 'traspatio'],
    tiene_leche: false, tiene_famacha: false, tiene_lote: true, tiene_colmena: false,
    vacunas: ['Newcastle', 'Bronquitis infecciosa', 'Gumboro', 'Influenza aviar', 'Viruela aviar', 'Marek', 'EDS'],
    kpis: ['pct_postura', 'mortalidad_pct', 'fcr', 'gdp_engorda', 'huevos_por_ave'],
  },
  abeja: {
    nombre: 'Abejas', emoji: '🐝', color: '#F9A825',
    gestacion_dias: 0, maduracion_meses: 0,
    categorias: [],
    razas: ['Italiana', 'Carniola', 'Buckfast', 'Africanizada', 'Criolla', 'Melipona beecheii', 'Scaptotrigona'],
    condicion_corporal: { min: 1, max: 5 },
    tipos_produccion: ['miel', 'cera', 'polen', 'propoleo', 'jalea_real', 'meliponicultura'],
    tiene_leche: false, tiene_famacha: false, tiene_lote: false, tiene_colmena: true,
    vacunas: [],
    kpis: ['kg_miel_colmena', 'tasa_supervivencia', 'varroa_control', 'reinas_confirmadas'],
    floraciones_yucatan: ['Tajonal', 'Dzidzilché', 'Tzalam', "Ja'abin", 'Flor de naranja', "Ts'its'ilché", 'Multifloral'],
  },
  equino: {
    nombre: 'Equinos', emoji: '🐴', color: '#4527A0',
    gestacion_dias: 340, maduracion_meses: 36,
    categorias: ['yegua', 'garanon', 'potro', 'potra', 'caballo_castrado', 'mula', 'burro'],
    razas: ['Cuarto de Milla', 'Pura Sangre', 'Azteca', 'Criollo', 'Appaloosa', 'Paint', 'Frisón', 'Cruza', 'Mulo'],
    condicion_corporal: { min: 1, max: 9 },
    tipos_produccion: ['trabajo', 'charreria', 'carrera', 'reproduccion', 'recreativo', 'carga'],
    tiene_leche: false, tiene_famacha: false, tiene_lote: false, tiene_colmena: false,
    vacunas: ['Encefalitis Venezolana', 'Encefalitis del Este', 'Influenza equina', 'Tétanos', 'Rabia', 'West Nile'],
    kpis: ['tasa_preñez', 'tasa_paricion'],
  },
  conejo: {
    nombre: 'Conejos', emoji: '🐰', color: '#00897B',
    gestacion_dias: 31, maduracion_meses: 5,
    categorias: ['coneja', 'semental', 'gazapo', 'engorda', 'reemplazo'],
    razas: ['Nueva Zelanda', 'California', 'Rex', 'Chinchilla', 'Angora', 'Mariposa', 'Cruza', 'Criollo'],
    condicion_corporal: { min: 1, max: 5 },
    tipos_produccion: ['carne', 'piel', 'pelo_angora', 'traspatio', 'mascota'],
    tiene_leche: false, tiene_famacha: false, tiene_lote: false, tiene_colmena: false,
    vacunas: ['RHDV2', 'Mixomatosis', 'Pasteurelosis'],
    kpis: ['gazapos_destetados_año', 'partos_año', 'mortalidad_predestete', 'fcr', 'tamaño_camada'],
  },
  diversificado: {
    nombre: 'Otros', emoji: '🦌', color: '#2E7D32',
    gestacion_dias: 200, maduracion_meses: 24,
    categorias: [],
    razas: [],
    condicion_corporal: { min: 1, max: 5 },
    tipos_produccion: ['cinegetico', 'carne', 'huevo', 'piel', 'exhibicion', 'conservacion'],
    tiene_leche: false, tiene_famacha: false, tiene_lote: false, tiene_colmena: false,
    vacunas: [],
    kpis: [],
  },
} as const;

export type SpeciesKey = keyof typeof SPECIES_CONFIG;
export type SpeciesConfig = typeof SPECIES_CONFIG[SpeciesKey];

export const SPECIES_LIST = Object.entries(SPECIES_CONFIG).map(([key, config]) => ({
  key: key as SpeciesKey,
  ...config,
}));

export function getSpeciesConfig(species: string): SpeciesConfig | undefined {
  return SPECIES_CONFIG[species as SpeciesKey];
}
