-- =============================================
-- HATOAI — SCHEMA COMPLETO v2.0
-- 9 ESPECIES | B2G | FINTECH-READY
-- =============================================

-- ========== CORE ==========

CREATE TABLE perfiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  nombre TEXT NOT NULL,
  telefono TEXT,
  email TEXT,
  rol TEXT DEFAULT 'productor',
  dependencia_gobierno TEXT,
  cargo_gobierno TEXT,
  avatar_url TEXT,
  onboarding_completado BOOLEAN DEFAULT false,
  idioma TEXT DEFAULT 'es',
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE ranchos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  nombre TEXT NOT NULL,
  estado TEXT NOT NULL,
  municipio TEXT NOT NULL,
  direccion TEXT,
  ubicacion_lat DECIMAL,
  ubicacion_lng DECIMAL,
  superficie_ha DECIMAL,
  tipo_produccion TEXT,
  especies_activas TEXT[] DEFAULT '{}',
  siniiga_upp TEXT,
  rfc TEXT,
  pgn_folio TEXT,
  logo_url TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE rancho_usuarios (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  rancho_id UUID REFERENCES ranchos(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  rol TEXT DEFAULT 'propietario',
  activo BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(rancho_id, user_id)
);

CREATE TABLE corrales (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  rancho_id UUID REFERENCES ranchos(id) ON DELETE CASCADE,
  nombre TEXT NOT NULL,
  tipo TEXT,
  capacidad INT,
  superficie_ha DECIMAL,
  tipo_pasto TEXT,
  estado TEXT DEFAULT 'activo',
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE animales (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  rancho_id UUID NOT NULL REFERENCES ranchos(id) ON DELETE CASCADE,
  numero_arete TEXT NOT NULL,
  id_siniiga TEXT,
  rfid TEXT,
  nombre TEXT,
  especie TEXT NOT NULL,
  sexo TEXT NOT NULL,
  categoria TEXT,
  raza TEXT,
  color TEXT,
  marcas TEXT,
  fecha_nacimiento DATE,
  fecha_nacimiento_estimada BOOLEAN DEFAULT false,
  fecha_ingreso DATE DEFAULT CURRENT_DATE,
  tipo_produccion TEXT,
  proposito TEXT,
  padre_id UUID REFERENCES animales(id),
  madre_id UUID REFERENCES animales(id),
  padre_externo TEXT,
  madre_externa TEXT,
  padre_genetico TEXT,
  registro_genealogico TEXT,
  estado TEXT DEFAULT 'activo',
  estado_reproductivo TEXT,
  estado_sanitario TEXT DEFAULT 'sano',
  corral_id UUID REFERENCES corrales(id),
  ubicacion_lat DECIMAL,
  ubicacion_lng DECIMAL,
  peso_nacimiento DECIMAL,
  peso_actual DECIMAL,
  fecha_ultimo_pesaje DATE,
  condicion_corporal DECIMAL,
  gdp_actual DECIMAL,
  origen TEXT DEFAULT 'nacido_en_rancho',
  programa_gobierno TEXT,
  folio_apoyo TEXT,
  precio_compra DECIMAL,
  proveedor TEXT,
  upp_origen TEXT,
  fierro TEXT,
  estatus_brucela TEXT,
  estatus_tuberculosis TEXT,
  paridad INT DEFAULT 0,
  num_pezones INT,
  linea_genetica TEXT,
  tipo_fibra TEXT,
  famacha_ultimo INT,
  uso_equido TEXT,
  alzada_cm DECIMAL,
  fecha_ultimo_herraje DATE,
  fecha_ultima_dental DATE,
  prueba_aie_vigente BOOLEAN,
  especie_diversificada TEXT,
  registro_uma TEXT,
  foto_url TEXT,
  fotos_adicionales TEXT[],
  notas TEXT,
  tags TEXT[],
  fecha_baja DATE,
  causa_baja TEXT,
  precio_venta DECIMAL,
  comprador TEXT,
  peso_venta DECIMAL,
  costo_acumulado DECIMAL DEFAULT 0,
  ingresos_acumulados DECIMAL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  created_by UUID REFERENCES auth.users(id)
);

CREATE TABLE lotes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  rancho_id UUID NOT NULL REFERENCES ranchos(id) ON DELETE CASCADE,
  nombre TEXT NOT NULL,
  especie TEXT NOT NULL,
  tipo TEXT,
  especie_ave TEXT,
  raza TEXT,
  cantidad_inicial INT NOT NULL,
  cantidad_actual INT,
  fecha_ingreso DATE DEFAULT CURRENT_DATE,
  fecha_nacimiento DATE,
  edad_ingreso_semanas INT,
  galpon_id UUID REFERENCES corrales(id),
  proveedor TEXT,
  costo_por_unidad DECIMAL,
  programa_vacunacion_inicial TEXT[],
  fecha_inicio_produccion DATE,
  fecha_estimada_venta DATE,
  programa_gobierno TEXT,
  estado TEXT DEFAULT 'activo',
  notas TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE produccion_lotes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  lote_id UUID NOT NULL REFERENCES lotes(id) ON DELETE CASCADE,
  rancho_id UUID NOT NULL REFERENCES ranchos(id),
  fecha DATE NOT NULL DEFAULT CURRENT_DATE,
  huevos_totales INT,
  huevos_rotos INT,
  huevos_sucios INT,
  huevos_doble_yema INT,
  huevos_vendibles INT,
  peso_promedio_muestra DECIMAL,
  muestra_cantidad INT,
  alimento_consumido_kg DECIMAL,
  agua_consumida_litros DECIMAL,
  mortalidad_dia INT DEFAULT 0,
  descarte_dia INT DEFAULT 0,
  causa_mortalidad TEXT,
  temperatura_galpon DECIMAL,
  humedad_galpon DECIMAL,
  notas TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE apiarios (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  rancho_id UUID NOT NULL REFERENCES ranchos(id) ON DELETE CASCADE,
  nombre TEXT NOT NULL,
  ubicacion_lat DECIMAL,
  ubicacion_lng DECIMAL,
  ubicacion_referencia TEXT,
  municipio TEXT,
  vegetacion_predominante TEXT[],
  distancia_agua TEXT,
  tipo_acceso TEXT,
  num_colmenas INT DEFAULT 0,
  certificacion_organica BOOLEAN DEFAULT false,
  certificadora TEXT,
  notas TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE colmenas (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  apiario_id UUID NOT NULL REFERENCES apiarios(id) ON DELETE CASCADE,
  rancho_id UUID NOT NULL REFERENCES ranchos(id),
  numero TEXT NOT NULL,
  id_siniiga_disco TEXT,
  tipo TEXT,
  especie_abeja TEXT DEFAULT 'apis_mellifera',
  num_cuerpos INT,
  raza_reina TEXT,
  color_marcaje_reina TEXT,
  edad_reina_meses INT,
  fecha_ultimo_requeening DATE,
  fecha_instalacion DATE,
  origen TEXT,
  estado TEXT DEFAULT 'activa',
  fortaleza TEXT,
  programa_gobierno TEXT,
  foto_url TEXT,
  notas TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE revisiones_colmena (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  colmena_id UUID NOT NULL REFERENCES colmenas(id) ON DELETE CASCADE,
  rancho_id UUID NOT NULL REFERENCES ranchos(id),
  fecha DATE NOT NULL DEFAULT CURRENT_DATE,
  inspector TEXT,
  reina_vista BOOLEAN,
  postura TEXT,
  huevos_frescos BOOLEAN,
  cuadros_cria INT,
  cuadros_miel INT,
  cuadros_polen INT,
  temperamento TEXT,
  celdas_reales BOOLEAN,
  celdas_reales_cantidad INT,
  varroa_conteo DECIMAL,
  varroa_metodo TEXT,
  varroa_nivel TEXT,
  enfermedades_observadas TEXT[],
  alimentacion_artificial TEXT,
  alimentacion_cantidad TEXT,
  notas TEXT,
  fotos TEXT[],
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE cosechas_miel (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  colmena_id UUID REFERENCES colmenas(id),
  apiario_id UUID NOT NULL REFERENCES apiarios(id),
  rancho_id UUID NOT NULL REFERENCES ranchos(id),
  fecha DATE NOT NULL,
  alzas_cosechadas INT,
  kg_miel_bruto DECIMAL,
  kg_miel_neto DECIMAL,
  kg_cera DECIMAL,
  kg_polen DECIMAL,
  gramos_propoleo DECIMAL,
  tipo_floral TEXT,
  humedad_pct DECIMAL,
  color TEXT,
  calidad TEXT,
  certificacion_organica BOOLEAN DEFAULT false,
  precio_kg DECIMAL,
  comprador TEXT,
  notas TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE pesajes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  animal_id UUID REFERENCES animales(id) ON DELETE CASCADE,
  rancho_id UUID NOT NULL REFERENCES ranchos(id),
  fecha DATE NOT NULL DEFAULT CURRENT_DATE,
  peso DECIMAL NOT NULL,
  metodo TEXT,
  condicion_corporal DECIMAL,
  gdp_calculado DECIMAL,
  registrado_por UUID REFERENCES auth.users(id),
  notas TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE produccion_leche (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  animal_id UUID REFERENCES animales(id) ON DELETE CASCADE,
  rancho_id UUID NOT NULL REFERENCES ranchos(id),
  fecha DATE NOT NULL DEFAULT CURRENT_DATE,
  litros_am DECIMAL,
  litros_pm DECIMAL,
  litros_total DECIMAL NOT NULL,
  ordena_numero INT,
  grasa_pct DECIMAL,
  proteina_pct DECIMAL,
  celulas_somaticas INT,
  mun DECIMAL,
  antibioticos_positivo BOOLEAN,
  notas TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE eventos_reproductivos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  animal_id UUID NOT NULL REFERENCES animales(id) ON DELETE CASCADE,
  rancho_id UUID NOT NULL REFERENCES ranchos(id),
  fecha DATE NOT NULL,
  tipo TEXT NOT NULL,
  celo_metodo TEXT,
  celo_intensidad TEXT,
  macho_id UUID REFERENCES animales(id),
  inseminador TEXT,
  pajilla_id TEXT,
  toro_raza_semen TEXT,
  tipo_semen TEXT,
  tanque_canastilla TEXT,
  protocolo_iatf TEXT,
  numero_servicios INT DEFAULT 1,
  donadora_id UUID REFERENCES animales(id),
  receptora_id UUID REFERENCES animales(id),
  laboratorio TEXT,
  calidad_embrion TEXT,
  estadio_embrion TEXT,
  metodo_diagnostico TEXT,
  resultado TEXT,
  dias_gestacion_estimados INT,
  num_fetos INT,
  palpador TEXT,
  facilidad_parto INT,
  presentacion TEXT,
  num_crias INT,
  retencion_placenta BOOLEAN,
  peso_destete DECIMAL,
  edad_destete_dias INT,
  metodo_destete TEXT,
  dias_gestacion_aborto INT,
  causa_probable TEXT,
  nacidos_vivos INT,
  nacidos_muertos INT,
  momificados INT,
  peso_camada DECIMAL,
  huevos_incubados INT,
  pollitos_nacidos INT,
  pct_eclosion DECIMAL,
  veterinario TEXT,
  notas TEXT,
  fecha_parto_esperada DATE,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE crias (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  evento_parto_id UUID NOT NULL REFERENCES eventos_reproductivos(id),
  animal_creado_id UUID REFERENCES animales(id),
  sexo TEXT,
  peso_nacer DECIMAL,
  vivo BOOLEAN DEFAULT true,
  nombre TEXT,
  notas TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE eventos_sanitarios (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  animal_id UUID REFERENCES animales(id),
  lote_id UUID REFERENCES lotes(id),
  colmena_id UUID REFERENCES colmenas(id),
  rancho_id UUID NOT NULL REFERENCES ranchos(id),
  fecha DATE NOT NULL DEFAULT CURRENT_DATE,
  tipo TEXT NOT NULL,
  campana TEXT,
  producto TEXT,
  lote_producto TEXT,
  dosis TEXT,
  via TEXT,
  proxima_aplicacion DATE,
  diagnostico TEXT,
  medicamento TEXT,
  duracion_dias INT,
  fecha_fin DATE,
  dias_retiro_carne INT,
  dias_retiro_leche INT,
  fecha_fin_retiro DATE,
  respuesta_tratamiento TEXT,
  tipo_prueba TEXT,
  resultado_prueba TEXT,
  laboratorio TEXT,
  mvtea TEXT,
  famacha_score INT,
  famacha_accion TEXT,
  varroa_conteo DECIMAL,
  varroa_metodo TEXT,
  causa_muerte TEXT,
  necropsia BOOLEAN,
  veterinario TEXT,
  costo DECIMAL,
  notas TEXT,
  fotos TEXT[],
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE inventario_alimentos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  rancho_id UUID NOT NULL REFERENCES ranchos(id),
  tipo TEXT,
  nombre TEXT NOT NULL,
  marca TEXT,
  proteina_pct DECIMAL,
  energia_kcal DECIMAL,
  cantidad_actual_kg DECIMAL,
  costo_por_kg DECIMAL,
  proveedor TEXT,
  fecha_caducidad DATE,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE consumo_alimento (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  rancho_id UUID NOT NULL REFERENCES ranchos(id),
  corral_id UUID REFERENCES corrales(id),
  lote_id UUID REFERENCES lotes(id),
  alimento_id UUID REFERENCES inventario_alimentos(id),
  fecha DATE NOT NULL DEFAULT CURRENT_DATE,
  cantidad_kg DECIMAL NOT NULL,
  num_animales INT,
  notas TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE movimientos_economicos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  rancho_id UUID NOT NULL REFERENCES ranchos(id),
  animal_id UUID REFERENCES animales(id),
  lote_id UUID REFERENCES lotes(id),
  tipo TEXT NOT NULL,
  categoria TEXT,
  subcategoria TEXT,
  monto DECIMAL NOT NULL,
  cantidad DECIMAL,
  precio_unitario DECIMAL,
  descripcion TEXT,
  comprador_vendedor TEXT,
  factura_folio TEXT,
  programa_gobierno TEXT,
  fecha DATE NOT NULL DEFAULT CURRENT_DATE,
  notas TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE programas_gobierno (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  nombre TEXT NOT NULL,
  dependencia TEXT,
  descripcion TEXT,
  estado TEXT,
  municipios TEXT[],
  fecha_inicio DATE,
  fecha_fin DATE,
  presupuesto DECIMAL,
  presupuesto_ejercido DECIMAL DEFAULT 0,
  meta_ranchos INT,
  meta_cabezas INT,
  meta_inseminaciones INT,
  meta_sementales INT,
  meta_colmenas INT,
  responsable TEXT,
  tipo TEXT,
  licencias_compradas INT DEFAULT 0,
  licencias_activadas INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE programa_ranchos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  programa_id UUID NOT NULL REFERENCES programas_gobierno(id),
  rancho_id UUID NOT NULL REFERENCES ranchos(id),
  fecha_inscripcion DATE DEFAULT CURRENT_DATE,
  tipo_apoyo TEXT,
  monto_apoyo DECIMAL,
  animales_entregados INT DEFAULT 0,
  compromiso TEXT,
  compromiso_cumplido BOOLEAN DEFAULT false,
  fecha_compromiso DATE,
  licencia_activa BOOLEAN DEFAULT false,
  fecha_activacion_licencia DATE,
  ultimo_login DATE,
  estado TEXT DEFAULT 'activo',
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE alertas (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  rancho_id UUID NOT NULL REFERENCES ranchos(id),
  animal_id UUID REFERENCES animales(id),
  lote_id UUID REFERENCES lotes(id),
  colmena_id UUID REFERENCES colmenas(id),
  tipo TEXT,
  mensaje TEXT NOT NULL,
  prioridad TEXT DEFAULT 'media',
  leida BOOLEAN DEFAULT false,
  generada_por TEXT DEFAULT 'sistema',
  fecha_alerta DATE,
  accion_sugerida TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE activity_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  rancho_id UUID REFERENCES ranchos(id),
  user_id UUID REFERENCES auth.users(id),
  tabla TEXT NOT NULL,
  registro_id UUID,
  accion TEXT NOT NULL,
  datos_anteriores JSONB,
  datos_nuevos JSONB,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE credit_score (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  rancho_id UUID NOT NULL REFERENCES ranchos(id),
  score_total INT,
  score_completitud INT,
  score_regularidad INT,
  score_productividad INT,
  score_financiero INT,
  score_antiguedad INT,
  score_sanitario INT,
  score_tamano INT,
  datos_calculo JSONB,
  calculado_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE documentos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  rancho_id UUID REFERENCES ranchos(id),
  animal_id UUID REFERENCES animales(id),
  tipo TEXT,
  nombre TEXT,
  archivo_url TEXT,
  fecha DATE DEFAULT CURRENT_DATE,
  notas TEXT,
  subido_por UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ DEFAULT now()
);
